### PR TITLE
fix "Import declaration conflicts with local declaration" error

### PR DESCRIPTION
**Pull request by jkruse14**
fix for issue:
https://github.com/types/mysql2/issues/32

Which was introduced by fixes/updates to typescript in 3.7

### CODE REVIEW

**Comment by unional** [comment]
thanks!

**Comment by kennethaasan** [comment]
Can this be released to a version? Ref: https://github.com/types/mysql2/issues/32#issuecomment-552285109

**Comment by unional** [comment]
@kennethaasan  `typings` is no longer maintained.
You should be able to get the latest by `npm install types/mysql2`

**Comment by jkruse14** [comment]
@kennethaasan - you should be good to go now. I added another update to use the master branch of this repo in types/mysql2:

https://github.com/types/mysql2/pull/35

**Comment by kennethaasan** [comment]
Great, thanks!

**Pull request merged**
