### PR TITLE
Adding newly added PoolOptions

### PR DESCRIPTION
**Pull request by franck-nadeau**
The following [PR](https://github.com/sidorares/node-mysql2/pull/1081) added two new options to mysql's Pool creation.

I am simply adding them to the library in this PR.

### CODE REVIEW

**Comment by unional** [comment]
From the description, does the `enableKeepAlive` also support `number`? 🌷

**Comment by unional** [comment]
thx!

**Comment by akleiber** [comment]
@unional how to get this released? :-)

**Comment by unional** [comment]
`typing` is deprecated, so to use this library, you should include it as github dependency directly.
Here is an article on how to do it:
https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a

There are some work lately on getting some bot to make these publish automatically, but I haven't hear much news about it in the last few weeks.

Another thing can be done is try to migrate this to DT.

**Pull request merged**
